# Generated by Django 5.0.3 on 2024-03-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectimp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=200)),
                ('ordem_grupo', models.IntegerField(max_length=200)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
