# Generated by Django 5.0.3 on 2024-03-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectimp', '0003_cadastrosubgrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogrupo',
            name='ordem_grupo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastrosubgrupo',
            name='nome_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo', to='projectimp.cadastrogrupo'),
        ),
        migrations.AlterField(
            model_name='cadastrosubgrupo',
            name='ordem_subgrupo',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CadastroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=200)),
                ('ordem_item', models.IntegerField()),
                ('ativo', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('list', 'Lista'), ('checkbox', 'Caixa de Seleção'), ('descritivo', 'Descritivo')], max_length=20)),
                ('contador', models.IntegerField()),
                ('Opcional', models.BooleanField(default=False)),
                ('Unidade', models.IntegerField()),
                ('nome_subgrupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrupo', to='projectimp.cadastrosubgrupo')),
            ],
        ),
    ]
