# Generated by Django 5.0.3 on 2024-03-28 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectimp', '0005_cadastrorespostaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrorespostaitem',
            name='nome_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='projectimp.cadastroitem'),
        ),
    ]
